### PR TITLE
Auto selects last metadata endpoint

### PR DESCRIPTION
**Pull request by weitzhandler**
Hi,

The endpoint drop-down contains the recent endpoints that were used.

image

When working on a server-client app that requires frequent changes to the server and re-generation of the client entities, any redundant click is tedious.
This PR changes the `ComboBox` to auto-select the first URL.

### CODE REVIEW

**Comment by weitzhandler** [comment]
I'll check it.

**Comment by weitzhandler** [comment]
I'm sorry, but I didn't test this.
I tried building the project but the launched VS instance doesn't have the extension installed.
I also had to uninstall the VSIX first to be able to build it.
What's the proper way of debugging it? It's been a long while since I've worked on VS extensions.

**Comment by paulodero** [comment]
> I'm sorry, but I didn't test this.
> I tried building the project but the launched VS instance doesn't have the extension installed.
> I also had to uninstall the VSIX first to be able to build it.
> What's the proper way of debugging it? It's been a long while since I've worked on VS extensions.

This is probably because of version conflict between installed connected service and the version in your project. instead of uninstalling you could increase the version in your local project and build. This has also been done in OData/master, please rebase and you will be good.

What is the VS version you are using?

**Comment by paulodero** [comment]
@weitzhandler It is advisable to rebase instead of merging master into your branch. Reason? to keep clean commit history and make it easier to merge back into master. One more thing, when PR is ready it is recommend to squash the commits into one commit.

**Comment by ElizabethOkerio** [comment]
@habbes @gathogojr @weitzhandler  how do you handle this for someone working with different endpoints and who doesn't want the field autopopulated?

**Comment by weitzhandler** [comment]
> It is advisable to rebase instead of merging master into your branch.

Ouch. Made it by mistake.
I have a few VS windows open and merged this one by mistake.


> One more thing, when PR is ready it is recommend to squash the commits into one commit.

OK

**Comment by weitzhandler** [comment]
@paulodero 

> This is probably because of version conflict between installed connected service and the version in your project. instead of uninstalling you could increase the version in your local project and build. This has also been done in OData/master, please rebase and you will be good.

I'm able to build, but when VS opens and trying to add a connected service, OData doesn't appear in the menu.

> What VS version are you using?
16.5.2

> It is advisable to rebase instead of merging master into your branch.

Sorry. Should I revert the merge?

**Comment by weitzhandler** [comment]
@ElizabethOkerio 

> I'll check deeper how this works, I shall hope the results are ordered by recently used. Anyway, it merely selects the first item as a suggestion, the rest of the values are there. It's an editable drop down.

**Comment by KenitoInc** [comment]
@weitzhandler This feature doesn't. Kindly have a look at it!

**Comment by weitzhandler** [comment]
> This feature doesn't. Kindly have a look at it!

What do you mean? I'm unable to debug ODataConnectedService, how do I do it?

**Comment by habbes** [comment]
@weitzhandler,could you try to rebase your branch with the latest updates from "master" and then try again? In order to debug the extension you must ensure that strong name verification is disabled for the binaries (check the README FAQ for instructions) and also the version you're debugging is different from the version you might already have installed on your VS.

**Comment by weitzhandler** [comment]
Started a fresh PR (#87) for this, too much dirt for such a minor change.

**Pull request closed without merging**
