### PR TITLE
Fix #96 : Updating multiple files prompts to overwrite each file

### LINKED ISSUE #96: Updating multiple files prompts to overwrite each file
### Describe the bug
When GenerateMultipleFiles is set to true and you updated the service, a prompt is shown for each existing file.  These prompts quickly fill the screen and cause the extension to crash (or at least it doesn't update any files).

#### Version of the Project affected
ODataConnectedService v0.8.0.0
VisualStudio Version v16.5.3
Microsoft.Odata.Client v7.6.x

#### To Reproduce
1. Add a new connected service for an OData data source
2. Click through the wizard until the final step (settings), then click Advanced settings
3. Check the box labeled Generate multiple files
4. Click finish
5. Right-click your connected service folder and choose update
6. Run through the wizard (or click finish)

#### Expected behavior
All of the generated files should be updated.

#### Actual behavior
A message box appears asking you to overwrite every file.  If there are enough of them, all message boxes disappear and nothing is updated.

#### Screenshots
image

### PR DESCRIPTION
**Pull request by unchase**
Fix #96

Also add logging for adding/updating files when generating multiple files.

For adding:

generate_multiple_files_add

For updating:

generate_multiple_files_update

### CODE REVIEW

**Comment by unchase** [comment]
@habbes @marabooy @KenitoInc @ElizabethOkerio @gathogojr @paulodero ready for review

**Comment by odero** [comment]
@unchase For future PRs if you could have the code formatting in a separate commit it would really help make the reviewing easier

**Comment by gathogojr** [comment]
@unchase I have merged your [other PR](https://github.com/OData/ODataConnectedService/pull/66). Kindly rebase

**Comment by unchase** [comment]
> @unchase I have merged your [other PR](https://github.com/OData/ODataConnectedService/pull/66). Kindly rebase

@gathogojr done!

**Pull request merged**
