### PR TITLE
feature/167-Description Annotation Support

### PR DESCRIPTION
**Pull request by KamyarP**
Added `GetDescriptionAnnotation` method in `ODataClientTemplate` class which returns Annotation of Term 'Description' if present. This value is then used in appropriate methods to write summary comments.
Encapsulated writing summary comments by adding `WriteDescriptionSummary` method in ODataClientCSharpTemplate/ODataClientVBTemplate.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/OData/ODataConnectedService?pullRequest=168) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/OData/ODataConnectedService?pullRequest=168) before we can accept your contribution.<br/><br/>:x: KamyarP [sign now](https://cla.dotnetfoundation.org/OData/ODataConnectedService?pullRequest=168)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/OData/ODataConnectedService?pullRequest=168) it.</sub>

**Comment by KamyarP** [comment]
@marabooy @Sreejithpin ready for review.
Also, I have signed the dnf CLA but status is still pending. not sure why.

**Review by habbes — APPROVED** [review]

**Comment by marabooy** [comment]
@KamyarP thank you for your contribution happy to review and get this merged.

**Review by marabooy — APPROVED** [review]

**Comment by habbes** [comment]
Hi @KamyarP apologies for the delays in merging this branch. We were in the process of migrating the extension to a new publisher. Could you rebase your branch and we will merge it.

**Review by habbes — APPROVED** [review]

**Pull request merged**
