### PR TITLE
Feature #127 : Option to show operation return types and list of operation parameters

### LINKED ISSUE #127: Option to show operation return types and list of operation parameters
### Is your feature request related to a problem? Please describe.
The user cannot see the operation return type and the list of operation parameters right now.

#### Describe the solution you'd like
Add an option (checkbox) that allows to show operation return types and list of operation parameters.

show_operation

#### Describe alternatives you've considered
Do not show this information.

#### Additional context
An added option will allow the user to see more information about the operations used if necessary.

### PR DESCRIPTION
**Pull request by unchase**
Add feature #127

show_operation

Added the tests below:

To **EdmHelperTests:**

- [x] `TestGetParametersString_WithEmptyParameters`;
- [x] `TestGetParametersString_WithSingleParameter`;
- [x] `TestGetParametersString_WithAFewParameters`.

To **BoolToVisibilityConverterTests:**

- [x] `Convert_ShouldReturnVisible_ForTrueValue`;
- [x] `Convert_ShouldReturnCollapsed_ForFalseValue`;
- [x] `Convert_ShouldThrowNotSupportedException_ForNonVisibilityTargetType`;
- [x] `Convert_ShouldThrowNotSupportedException_ForNonBooleanValue`;
- [x] `ConvertBack_ShouldThrowNotSupportedException`.

### CODE REVIEW

**Comment by unchase** [comment]
@habbes @marabooy @KenitoInc @ElizabethOkerio @gathogojr @paulodero ready for review

**Comment by KenitoInc** [comment]
@unchase Should be button be unchecked when you leave the Operations page?

**Comment by unchase** [comment]
> @unchase Should the button be unchecked when you leave the Operations page?

@KenitoInc It does not matter, because it only affects the display for the user, and not the generation.

**Comment by habbes** [comment]
@unchase please update this branch

**Comment by unchase** [comment]
> @unchase please update this branch

@habbes Updated.

**Pull request merged**
