### PR TITLE
Fix #135 : Collection of enum properties is not added to related types Dictionary for structured types

### LINKED ISSUE #135: Collection of enum properties is not added to related types Dictionary for structured types
### Describe the bug
Selecting a schema type does not include its related schema types (enums) from collection of enum properties. This properties will not be added to generated code. Will get compilation errors.

#### Version of the Project affected
ODataConnectedService v0.10.x

#### To Reproduce

1. Create an OData Connected Service based on the [Microsoft Graph service](https://graph.microsoft.com/v1.0/$metadata);
2. Move to the schema types page, all types should be selected by default;
3. Deselect all schema types;
4. Select, for example, `managedAppRegistration` schema type (which has `Collection(graph.managedFlaggedReason)` property);
4. See that `managedAppFlaggedReason` does not selected;
5. Click **Finish** to generate code;
6. Try to build project.

#### Expected behavior
Selecting schema types should select all its required types.

#### Actual behavior
Selecting schema types does not select all its required types.

#### Screenshots
* Schema types Selection:

bug

* Example1 - `managedAppRegistration` type with `Collection(graph.managedFlaggedReason)` property:

bug3

* Example2 - `managedAppProtection` type with `Collection(graph.managedAppDataStorageLocation)` property:

bug4

* Compilations errors:

bug2

### PR DESCRIPTION
**Pull request by unchase**
Fix #135

Added the tests below:

To **SchemaTypesViewModelTests:**

- [x] `LoadSchemaTypes_ShouldAddRelatedPropertyTypeForStructuredType_WherePropertyIsCollectionOfEnum`.

### CODE REVIEW

**Comment by unchase** [comment]
@habbes @marabooy @KenitoInc @ElizabethOkerio @gathogojr @paulodero ready for review

**Comment by marabooy** [comment]
@unchase can you rebase and fix the conflicts

**Comment by unchase** [comment]
> @unchase can you rebase and fix the conflicts

@marabooy rebased.

**Comment by ElizabethOkerio** [comment]
@unchase the issue is still there.. seems it has no been fixed. When I select managedAppRegistration schema type, this managedAppFlaggedReason property does not get selected hence getting the error you described on the issue.

**Comment by KenitoInc** [comment]
@unchase As @ElizabethOkerio has stated, I also tested and the issue doesn't seem to be fixed. I also tested with a different CSDL and same issue persists.

**Comment by unchase** [comment]
> @unchase the issue is still there.. seems it has not been fixed. When I select `managedAppRegistration ` schema type, this `managedAppFlaggedReason`property does not get selected hence getting the error you described on the issue.

@ElizabethOkerio @KenitoInc Strange, because the issue does not reproduce:
issue

**Comment by habbes** [comment]
The PR worked well on my end using the experimental instance. Maybe there was issue when generating the signed vsix on CI.

**Pull request merged**
