### PR TITLE
Implement "No tracking" option for odata-cli

### LINKED ISSUE #269: odata-cli tracking option is missing
As per #247

--no-tracking |-n - disables entity and property tracking

Should assume that UseDataServiceCollection would be true, but never assigned or supported on CLI commands, so defaults to false producing a proxy without change tracking enabled

### PR DESCRIPTION
**Pull request by marcmognol**
# Motivation

Fix #269 

# Modifications
- Add new option --no-tracking to control the UseDataServiceCollection property of the generator
- Default to false to be aligned with the naming of this option, so it is a breaking change

### CODE REVIEW

**Comment by ElizabethOkerio** [comment]
@marcmognol  check this comment https://github.com/OData/ODataConnectedService/pull/339#issuecomment-1527068277 and update the command like so.

**Comment by marcmognol** [comment]
> @marcmognol  check this comment https://github.com/OData/ODataConnectedService/pull/339#issuecomment-1527068277 and update the command like so. 

I have renamed the option.

**Review by KenitoInc — APPROVED** [review]

**Comment by ElizabethOkerio** [comment]
@marcmognol  Thanks for the contribution.

**Comment by marcmognol** [comment]
> @marcmognol  Thanks for the contribution. 

You're welcome.
Do you know when this will be released or is there any nightly build ?

Thanks

**Pull request merged**
