### PR TITLE
Add ability for choosing local metadata files

### PR DESCRIPTION
**Pull request by unchase**
browse

### CODE REVIEW

**Comment by habbes** [comment]
Hi @unchase, thanks for this contribution. Could you rebase your branch.

**Comment by unchase** [comment]
> Hi @unchase, thanks for this contribution. Could you rebase your branch.

@habbes done.

**Comment by marabooy** [comment]
@unchase  could you mark the branch as ready for review if the branch is ready. Is there any pending work?

**Comment by unchase** [comment]
> @unchase could you mark the branch as ready for review if the branch is ready. Is there any pending work?

@marabooy Tell me, how can I do this ?

labels

**Comment by marabooy** [comment]
Is the cog on the right accessible? If not just mention @habbes , @ElizabethOkerio  or @paulodero and they will do it for you.
image

**Comment by marabooy** [comment]
> @unchase The button allows you to change the service endpoint even when the text field is disabled. I think the button should be disabled when the text field is disabled.
> 
> Everything else looks fine to me.
@habbes maybe for files we wan't to leave it that way? as they may have moved the file or deleted it. unless if we want to copy the file to the project. It may be hard to enforce the same file location for local files. 
@unchase  I think what we can do (in my opinion) is if the file is local leave it as is but if it was a url disable the button.

**Comment by habbes** [comment]
@marabooy @unchase good point, being able to update the file sounds a like a good idea.

**Comment by unchase** [comment]
> Is the cog on the right accessible? If not just mention @habbes , @ElizabethOkerio or @paulodero and they will do it for you.
> image

Why not give contributors such an opportunity? (issue #44)

**Comment by unchase** [comment]
@habbes @marabooy 
Done.
web

file

**Pull request merged**
